version: '3.0'
services:
  api:
    image: mohamedamineblibech/backend_crud
    container_name: api
    ports:
      - "3700:3700"
    command: npm run start:dev  
    environment:
      MONGO_URI: mongodb://crud:crud@db:27017
    volumes:
      # - "./server/:/app"  
      - "/app/node_modules"
    networks:
      - crud_network

  web:
    image: mohamedamineblibech/frontend_crud
    container_name: web
    volumes:
      - web-root:/app/build
      - "./client/:/app"  
      - "/app/node_modules"
    networks:
      - crud_network
      
  db: 
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: crud
      MONGO_INITDB_ROOT_PASSWORD: crud
    volumes:
      - db-data:/data/db
    networks:
      - crud_network

  webserver:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - web
      - api
    networks:
      - crud_network
      
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email blibechmedamine@gmail.com --agree-tos --no-eff-email --force-renewal -d testt3.ddns.net
    networks:
      - crud_network

volumes:
  db-data:       
  certbot-etc:
  certbot-var:
  web-root:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/deploy-docker-MERN/dhparam/
      o: bind

networks:
  crud_network:
    driver: bridge


      
    
