version: '3.0'
services:
  api:
    build: ./server/
    container_name: api
    ports:
      - "3700:3700"
    command: npm run start:dev 
    environment:
      MONGO_URI: mongodb://crud:crud@db:27017
    volumes:
#      - "./server/:/app"  
      - "/app/node_modules"
    networks:
      - crud_network
    
  web:
    build: 
      context: ./client/
    container_name: web
    ports:
      - "3534:3000"
    command: npm run start
    volumes:
      - "./client/:/app"
      - "/app/node_modules"
    networks:
      - crud_network
  db: 
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: crud
      MONGO_INITDB_ROOT_PASSWORD: crud
    volumes:
      - db-data:/data/db
    networks:
      - crud_network

volumes:
  db-data:       

networks:
  crud_network:
    driver: bridge


      
    
